-- Create roles
CREATE OR REPLACE ROLE ADMIN;
CREATE OR REPLACE ROLE ADVISOR;

-- Grant privileges to ADMIN (full access)
GRANT USAGE ON DATABASE JORDI_DB TO ROLE ADMIN;
GRANT USAGE ON SCHEMA JORDI_DB.PUBLIC TO ROLE ADMIN;
GRANT CREATE TABLE ON SCHEMA JORDI_DB.PUBLIC TO ROLE ADMIN;
GRANT CREATE VIEW ON SCHEMA JORDI_DB.PUBLIC TO ROLE ADMIN;
GRANT CREATE FUNCTION ON SCHEMA JORDI_DB.PUBLIC TO ROLE ADMIN;

GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA JORDI_DB.PUBLIC TO ROLE ADMIN;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA JORDI_DB.PUBLIC TO ROLE ADMIN;

-- Grant privileges to ADVISOR (read-only)
GRANT USAGE ON DATABASE JORDI_DB TO ROLE ADVISOR;
GRANT USAGE ON SCHEMA JORDI_DB.PUBLIC TO ROLE ADVISOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA JORDI_DB.PUBLIC TO ROLE ADVISOR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA JORDI_DB.PUBLIC TO ROLE ADVISOR;
