-- Create External OAuth integration for Azure AD
CREATE OR REPLACE SECURITY INTEGRATION JORDI_SNOWFLAKE_CONNECTOR
  TYPE = EXTERNAL_OAUTH
  ENABLED = TRUE
  EXTERNAL_OAUTH_TYPE     = AZURE
  AZURE_AD_APPLICATION_ID = '6c0517cd-edca-4d08-8d8e-b90f08eb9d5e'  -- client ID
  AZURE_TENANT_ID         = 'dac7020d-cf47-4b79-9f0d-facb19ad7102'; -- tenant ID

-- Verify the integration
SHOW INTEGRATIONS LIKE 'JORDI_SNOWFLAKE_CONNECTOR';
DESC INTEGRATION JORDI_SNOWFLAKE_CONNECTOR;

SELECT SYSTEM$FEATURE_LIST();

SELECT CURRENT_VERSION(), CURRENT_ACCOUNT(), CURRENT_REGION(), EDITION();
